version: '3'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app-notifications
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/notifications
    volumes:
      - ./:/var/www/notifications
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-notifications
    restart: unless-stopped
    tty: true
    ports:
      - "8001:81"
    volumes:
      - ./:/var/www/notifications
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #RabbitMQ Service
  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./:/var/www/notifications


  # #MySQL Service
  # db:
  #   image: mysql:latest
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   # ports:
  #   #   - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ""
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #     - ./mysql/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local